### ISSUE TITLE
很好用，支持一下。

### ISSUE THREAD

**Issue by translate-a-book** [xulihang/BasicCAT#10]
API无缝衔接多种机器翻译，好多机器翻译还有免费额度。
导入导出直接翻译idml文件，简单到不可思议。
不知道能不能翻译软件界面？

**Comment by xulihang** [comment]
谢谢，本地化BasicCAT需要参考[这个帖子](https://www.b4x.com/android/forum/threads/b4x-localizator-localize-your-b4x-applications.68751/#content)对代码中的文字封装，然后导出xlsx供翻译。因为英文版界面大家应该都能看懂，就没有优先做本地化工作，等我过段时间再搞。如果英文界面有问题也欢迎指出

**Comment by translate-a-book** [comment]
谢谢回复。其实本来是想问一下能不能用BasicCAT来翻译别的软件？看了帖子，再继续研究。


另外，我在微信公众号中转载了您的一篇文章，也提到了BasicCAT。
https://mp.weixin.qq.com/s/Iv0SIFv-iSRYdy39BfDRJg，请查阅，侵删。




------------------

译万卷书 行万里路

译本书队正在参加

第二届艺果杯翻译技术大赛 

暨实战翻译项目管理大赛 

请大家多多支持！！！

 

 
 
 
------------------ Original ------------------

**Comment by xulihang** [comment]
翻译别的软件要看具体使用的语言和针对的平台，比如Android的XML文件等，这类可以用okapi处理成xliff文件进行翻译。我还整理过一篇iOS程序的本地化流程：<https://blog.xulihang.me/localize-an-iOS-app-under-the-guidance-of-memoq-product-manager/>

一般软件本地化是把要翻译的文本导出为xlsx之类的表格给译员翻译的，这样译员要做的就比较简单了。

文章我看到的，欢迎传播，协议遵守CC-BY-SA-3.0

**Comment by translate-a-book** [comment]
你好，
      我关注到一款免费机器翻译软件：云译。https://cloudtranslation.com/static/api_zh-cn.html#_6


如果在BasicＣＡＴ调用的话，是不是需要插件。
如果不麻烦的话，请您开发一个插件。谢谢。






------------------

译万卷书 行万里路

译本书队正在参加

第二届艺果杯翻译技术大赛 

暨实战翻译项目管理大赛 

请大家多多支持！！！

 

 
 
 
------------------ Original ------------------

**Comment by xulihang** [comment]
这个机器翻译API不用密钥，比较容易实现，插件代码：https://github.com/xulihang/BasicCAT/plugins/cloudtranslationMT/


下载：[cloudtranslationMTPlugin.zip](https://github.com/xulihang/BasicCAT/files/3590311/cloudtranslationMTPlugin.zip)

**Comment by translate-a-book** [comment]
神速！！！
谢谢。
 




------------------

译万卷书 行万里路

译本书队正在参加

第二届艺果杯翻译技术大赛 

暨实战翻译项目管理大赛 

请大家多多支持！！！

 

 
 
 
------------------ 原始邮件 ------------------
发件人: "xulihang"; 
发送时间: 2019年9月9日(星期一) 晚上7:56
收件人: "xulihang/BasicCAT"; 
抄送: "translate-a-book"; "Author"; 
主题: Re: [xulihang/BasicCAT] 很好用，支持一下。 (#10)

 


这个机器翻译API不用密钥，比较容易实现，插件代码：https://github.com/xulihang/BasicCAT/plugins/cloudtranslationMT/
 
下载：cloudtranslationMTPlugin.zip
 
&mdash;

**Comment by xulihang** [comment]
下次有新的问题或者功能请求请开一个新的issue，这个issue就关闭了。
