### ISSUE TITLE
直接在word上做的译文，有没有可能实现导入BasicCAT来做校订？

### ISSUE THREAD

**Issue by abtxu** [xulihang/BasicCAT#13]
这个问题困惑了很久，接触CAT之前做的很多翻译了，有没有可能找到某种方式来导入到翻译CAT程序里边校订呢？总不能一句句复制译文放进去，效率太低了。有没有可能先做成tmx记忆库然后导入Basic CAT来处理？

**Comment by xulihang** [comment]
我是这样想的：做一个纯文本的对齐，之后再用CAT工具打开原文文件，使用翻译记忆预翻译。这样的话可能需要重新处理一些格式的问题，如果Word没有很多复杂的格式还是比较好办的。我写的对齐工具[Aligner](https://www.basiccat.org/new-tool-bitext-aligner/)能做对齐，但格式标签因为比较难就没做保留。

要显示审校后的文件在哪些地方做了修改，可以使用Word的比较功能或者使用git对比BasicCAT工作文件的版本。BasicCAT没有Trados那样的修订编辑界面，对审校的支持不是很完善，我在使用说明里写的方法是把BasicCAT中的片段导出到Word里去审校的。

另外可以的话，您提供给我几份文件，我再研究下，看看怎么完善。

**Comment by abtxu** [comment]
非常感谢您及时的回复！做对齐不难，我一般用的是ABBYY Aligner 2.0，快捷键操作非常方便。
困难的是怎么做到让这个对其之后的文件成为翻译项目的一部分，我看大部分CAT软件都做不到这一点，也没有意向去这么做。但其实这是一个非常现实的需求，相当多的译者就是在随便什么文本处理器里边昨晚翻译的，而主流CAT软件都不去考虑这些自己的功能怎么去和这种情况衔接起来。

[PREFACE 序言.docx](https://github.com/xulihang/BasicCAT/files/4169450/PREFACE.docx)

**Comment by xulihang** [comment]
这个Word里是一个段落对齐的表格，那还是比较容易处理的。把表格复制到excel里可以当做翻译记忆导入BasicCAT，不过这样是段落对齐，可以用对齐软件精细化到句。然后把Word的译文列的字体设置为隐藏，把Word导入BasicCAT做翻译。如果翻译记忆是段落对齐的，导入前在BasicCAT的项目设置里把“Enable sentence-level segmentation“取消勾选以关闭导入时的自动分句。

![1](https://user-images.githubusercontent.com/5462205/74023111-d21bf580-49d9-11ea-89c9-44c364af85e5.png)

**Comment by abtxu** [comment]
非常感谢！BasicCat直接导入这个docx文件的话，原文和译文都挤在左边。我删掉了中译文之后就能直接把docx文件导入。但我的目的就是想让这个已经实现对齐的docx文件重新变成一个BasicCat的翻译项目，删掉译文就没有意义了。
我看到你的截图中的文件格式变为xlf，就试着用Goldpan Editor 3.3 做了一个，但还是只能显示用英语

原文。
[序言.zip](https://github.com/xulihang/BasicCAT/files/4176633/default.zip)

**Comment by xulihang** [comment]
BasicCAT导入xliff只处理原文，不管译文。译文要做成翻译记忆，用预翻译填充。

**Comment by abtxu** [comment]
非常感谢！使用预翻译导入成功，可以关闭这个issue了。
