### ISSUE TITLE
机器翻译

### ISSUE THREAD

**Issue by abtxu** [xulihang/BasicCAT#14]
![图片](https://user-images.githubusercontent.com/48761002/74601973-e00afe00-50de-11ea-8d30-51047fdb5ba3.png)
机器翻译在安装插件之后不能使用，选中之后就出现截图中的情况。doc搜索后也没有找到解答。

**Comment by xulihang** [comment]
这是一个交互设计的缺陷，需要点击非选框处调出参数填写对话框，把参数填写完整才能启用机器翻译引擎。

还有自带的机器翻译插件是最全和最新的，除非开发了新的插件，不用手动安装
