### ISSUE TITLE
有没有可能让机器翻译加载术语库或者记忆库？

### ISSUE THREAD

**Issue by abtxu** [xulihang/BasicCAT#15]
比如搜狗翻译的长处是句法，短处和一般的机器翻译类似，很多词汇的翻译没法做到对语境足够敏感。机器翻译能够做到自定义术语库和记忆库的话就能大大提高翻译的准确率了。

**Comment by xulihang** [comment]
这个需要使用定制机器翻译，微软、谷歌、IBM、亚马逊和阿里都是提供这个功能的，你可以先看下阿里的机器翻译自学习平台，支持上传翻译记忆和词典：<https://help.aliyun.com/document_detail/124960.html>，这方面我也还没有进行尝试，主要是没有翻译专有领域的需求。
