### ISSUE TITLE
字体无法修改

### ISSUE THREAD

**Issue by abtxu** [xulihang/BasicCAT#16]
设置字体点应用之后字体没有变化，重启之后也没有。 Dark主题是生效的。试了几次都是这样。

**Comment by xulihang** [comment]
我测试是可以的，已经显示在编辑界面的字体不会立即改变，需要拖动进度条或者切换文件才能看到效果。

**Comment by abtxu** [comment]
我的情况是font picker里边选了字体和大小，点ok，然后再点进去看看的话，仍旧是原来的大小。应该就是这个原因导致的。
BasicCAT什么时候下一波更新来着？

**Comment by xulihang** [comment]
再点进去看字体大小是默认的15。
最近主要精力在[图片翻译工具](https://www.basiccat.org/zh/imagetrans/)上，BasicCAT暂时没有更新计划。

**Comment by abtxu** [comment]
感谢！又加入了一个文件，然后切换文件，确实解决了字体没法修改的问题。这个issue可以关闭了。
