### ISSUE TITLE
译文的Segmentation出现的几种问题

### ISSUE THREAD

**Issue by abtxu** [xulihang/BasicCAT#17]
为了尽量格式带来的减少干扰，我用的是txt格式。导入之后常见的问题是：如果句尾包含数字（其实是word文档的脚注），括号，甚至这种“....”号， 往往会出问题。

如“largely . . . reminding”会变成：
“largely .
.
.
reminding

如果句子结尾是数字，那么前后两句会并在一起。

有没有办法避开这类分句的错误？

**Comment by xulihang** [comment]
有空格这个是原文不够规范，数字结尾的确是不足的地方。这个需要定义SRX分割文件，可以用[ratel](http://okapiframework.org/wiki/index.php?title=Ratel)修改项目文件夹config文件夹里的segmentationRules.srx，规则都是正则写的，比较复杂。BasicCAT的SRX算法有不完善的地方，可能不能和ratel中显示的效果一致。

**Comment by xulihang** [comment]
规则要生效需要重启BasicCAT或者打开一个语言方向不一样的项目

**Comment by xulihang** [comment]
以下两个commits已经修复了句段分割的问题：
fabfe5d71347dfc8ea012543339038afba6cde0c
4db5ab37930551e666411607558a591b8bb5aa96

适合上述情况的srx文件，需要放到项目的config文件夹：

[segmentationRules.zip](https://github.com/xulihang/BasicCAT/files/4274517/segmentationRules.zip)
