### ISSUE TITLE
[feature request] NiuTrans API接口免费开放及域名调整

### ISSUE THREAD

**Issue by ustczzh** [xulihang/BasicCAT#19]
**1. 申请升级niutrans api接口。7月15日之后原接口将无法使用。**
**2. 建议增加niutrans免费接口，方便个人翻译用户免费使用。**

见官方公告（https://niutrans.com/changeDetails）

由于本次更新已将平台域名niutrans.vip变更为niutrans.com，相应地，API接口域名也已同步变更为api.niutrans.com，接口访问地址示例如下：

原网址：http(s)://api.niutrans.vip/NiuTransServer/translation

体验免费API服务请接入免费接口：http(s)://free.niutrans.com/NiuTransServer/translation

支持请求长度：2000字符；

支持QPS数量：3；

用户调用免费接口所产生的字符消耗将不予计费。

希望保持原有服务体验建议接入高级接口：http(s)://api.niutrans.com/NiuTransServer/translation

支持请求长度：5000字符；

支持QPS数量：50；

高级接口将按照用户翻译的字符数量计费。

*如需了解新接口详情，请访问https://niutrans.com/documents/develop/develop_text

niutrans.vip域名的接口将会保留至7月15日，后续将停止服务。为不影响您的正常使用，请在有效期内尽快完成相关工作的调整。

**Comment by xulihang** [comment]
好的，我会更新相关插件

**Comment by xulihang** [comment]
已经更新了：https://github.com/xulihang/BasicCAT/releases/download/plugins/all_plugins.zip

默认使用免费模式，需要使用高级模式则在参数的free mode中填入no。

**Comment by xulihang** [comment]
免费模式的QPS太低，不能用于预翻译，单句的调用应该都没问题。

**Comment by ustczzh** [comment]
非常感谢，已经适用，niutrans的免费版可以正常使用。
有免费版就很谢天谢地了！
现在主要单句调用，用着还行！非常感谢作者的软件！

最近使用BasicCAT适用了几个国内的机器翻译引擎。
有道没有免费，只有一次性赠金，质量不行。
搜狗深智没有免费流量，只有一次性赠金，质量不错。
腾讯云每月免费500万，质量不错。
百度翻译有免费，不限流量，质量不错。
小牛翻译新改版有免费版，不限流量，质量不错。
阿里云每月100万免费，质量一般。
现在主要就用这几个免费的。

**Comment by ustczzh** [comment]
顺便反应几个界面的小问题，不知道值不值得另开issue。
1. 【稍有不便】打开文件对话框没有记忆功能，每次打开软件，也没有历史记忆，需要重新找到翻译工程所在文件夹。导入文件时也都没有记忆功能。
2. 【稍有不便】软件的自动备份功能无法控制文件夹大小。连续使用半个月，从早到晚，电脑不关，软件不管，发现bak文件夹已经有了十几个g，还由于设置了坚果云的自动同步，全部被同步了。
3. 【影响使用】“Edit the source text of the current segment”功能有些问题。修改后无法保存，必须在修改后，立即切换别的文件，再切回来才会保存成功（即使这样也成功率不高），监控json文件的更改，更改会成功，但是很快又会被改回原来的。
4. 【影响使用】默认设置的快捷键不够用，建议增加自定义快捷键。Edit菜单下的各种功能都很常用，还有2个git commit命令。
5. 【稍有不便】在source中回车会切分segment，但是有时候多次回车后会生成空白segment，却无法用del删去空白segment，会提示错误。
6. 【稍有不便】界面各窗口的分割位置没法记忆，每次打开软件需要重新调整。

再次感谢作者！

**Comment by xulihang** [comment]
修改原文失败应该是因为光标在原文的编辑框里，失去焦点后会恢复原文。这点有待改进。
其它的易用性的建议之前也有人提过，我有空了会改进。

**Comment by ustczzh** [comment]
太好了，原来光标放置target框里，就可以直接更改原文了。舒服了！

**Comment by xulihang** [comment]
[1.8.0](https://www.basiccat.org/zh/1-8-0/)增加了记忆之前位置的功能

**Comment by ustczzh** [comment]
最近一直在用BasicCAT，软件还是很好用的，除了偶尔java会提示内存溢出。

1，之前问过快捷键的问题，默认的Ctrl+1会选择TM框的第一条，但是这个是与该框的排序有关，我设置了4个tm，其中的niutrans不管怎么排序都不会是第一个。能否添加Ctrl+2，Ctrl+3，Ctrl+4快捷键分别添加tm框的后面几条。或者手工指定排序？翻译工作量大，用键盘快捷键比较方便，右手基本不离键盘，不用去点鼠标。

2，还有发现新版光标位置有些奇怪，用鼠标点击source框和target框，每次光标都不会出现在我点击的位置，要么隔几个字母，或者出现在行尾。我用鼠标点击一般都是选择单词和译文后添加术语表，现在每次点击都要多点1次或2次，才能正确选中。

**Comment by xulihang** [comment]
46455183206113534a76ae7ef5f2a9014cb1ff98 修复光标问题
14c35a6c22e9c05d93a86f513919f941d1bbfbfb 添加调用机器翻译或者翻译记忆的快捷键，CTRL+[1-5]
3c0fe9e4596f7793bb03f42fc5318be4430510b0 添加切换原文和译文编辑区域的快捷键CTRL+TAB

**Comment by ustczzh** [comment]
下载了B4J尝试编译，不过少了好多库。不太会折腾java，还是等待新的release吧。

**Comment by ustczzh** [comment]
还是关于按键的问题。按下Alt键时会激活菜单，焦点会转移到File上。但是如果经常使用Alt+Tab切换多任务，比如参考文献，浏览器或者其它程序，这回导致切换回BasicCAT时，焦点不再是原来的编辑框，而是转移到File上，而不再能用方向键控制光标，必须重新点击输入框。
建议是弹起Alt键时再激活菜单。我看了很多软件，其实都是这样设计的。弹起Alt键时激活菜单，这个与Alt+Tab不冲突。

**Comment by xulihang** [comment]
新版本发布了。我测试Alt+Tab切换到别的窗口后再切回来，编辑框还是处于激活状态的

**Comment by ustczzh** [comment]
1，已经测试了。1.8.4的绿色版打包有问题，BasicCAT.jar还是1.8.3版。我重新下载了x64安装版，这个正常。之前的反应的问题都已经修复了。
2，目前1.8.4版，使用Alt+Tab切换后（实际是按下Alt键后），光标仍然是留在编辑框，但是焦点已经转移到File上了，这时通过方向键试图移动光标，但是实际上会移动焦点到Edit,project。更好的办法是在Alt键弹起时再切换焦点。
3，有没有打算建立QQ、Telegram或者Discord群，方便沟通？

**Comment by xulihang** [comment]
多谢提醒，跨平台版的zip我更新了。
切换窗口的问题我做了更新，当窗口重新获得焦点时，会先聚焦在菜单以取消ALT状态，然后再聚焦回编辑框，这样就没问题了：c7b42ba9dff70bfacec62872fed840ba58b7ad28。
没建QQ群主要是觉得聊天记录不能永久保存，不如在GitHub上发issue。Telegram没用过，不知道怎么样。

**Comment by ustczzh** [comment]
好的，非常感谢。
1，Telegram的聊天记录永久保存，建群、公众号/频道随意，还有很多机器人可用，唯一问题是需要翻墙。我用ehforwarderbot把微信记录转到Telegram上，这样所有聊天记录也能永久保存。Discord更像是论坛，可以自己开设板块和不同分区，聊天记录应该也是永久保存，后入群的人可以随时看到之前的内容。但好像不能用机器人，也必须翻墙。
2，不知道java能不能处理按键的按下（键值注册）和抬起（键值释放）这两种情况。但是我还是觉得更改Alt键的行为是更好的选择。
我这里找了几个软件尝试了一下，按下和抬起Alt键的行为有2个，一个是下划线显示热键，一个是焦点改变。但是具体行为有两类：
A1，按下Alt：下划线显示。
A2，抬起Alt：焦点移至菜单。
A3，按下Alt：下划线隐藏，焦点返回编辑框。
A4，抬起Alt：无动作。

B1，按下Alt：下划线显示。
B2，抬起Alt：焦点移至菜单。
B3，按下Alt：无动作。
B4，抬起Alt：下划线隐藏，焦点返回编辑框。

A类软件：Everything，WinScp，Win10任务管理器，VS Code，Zotero
B类软件：FileLocator Pro，

绝大多数软件都是A类。但是不管怎样，应该都跟窗口焦点无关。

还是等新的release版测试一下。非常感谢！

**Comment by xulihang** [comment]
更新了1.8.5。最近没空了，除非有大的问题，暂时不会更新了
