### ISSUE TITLE
建议增加google 机器翻译免费插件，可以用定向到网页的方法去解决；同时支持输出双语对照的格式，这个会方便很多

### ISSUE THREAD

**Issue by Joe007007007** [xulihang/BasicCAT#22]
建议增加google 机器翻译免费插件，可以用定向到网页的方法去解决；同时支持输出双语对照的格式，这个会带来很多便利。

**Comment by xulihang** [comment]
双语对照可以使用Tools->Batch->Generate Bilingual Files (for xliff)功能试试看，
网页版机器翻译我暂时不想研究怎么集成

**Comment by xulihang** [comment]
今天有空，就把网页版机器翻译插件实现了一下：5ae95cf37bb252f0a5322a417ebfc71a1b7a4601

效果还是不错的，可以使用网页版的谷歌和百度，翻译结果可以和其他用API的机器翻译一样直接显示在列表中：

![basiccat_mtweb](https://user-images.githubusercontent.com/5462205/97874788-8160df80-1d54-11eb-9beb-4bdb25d43fa3.png)

**Comment by xulihang** [comment]
插件下载：
[webmt_plugins.zip](https://github.com/xulihang/BasicCAT/files/5475405/webmt_plugins.zip)

使用方法：
网页版机器翻译的URL里如果包含了原文译文语言和文本的参数，那可以较为容易地调用。译文也可以通过解析网页直接提取。
Params那个文本框里包含如下内容：
```
auto,zh-CN,translation
Hello World!
```

它们依次是源语言代码、目标语言代码、最后的翻译结果的class name以及文本。
源语言和目标语言的代码需要自己根据情况进行调整

如果要更换别的机器翻译引擎，需要修改URL Template（模板）以及Params（参数），这里提供一个百度的例子：

URL Template: 
```
https://fanyi.baidu.com/#{sourceLang}/{targetLang}/{text}
```
Params: 
```
en,zh,trans-content
Hello World!
```

**Comment by Joe007007007** [comment]
> 双语对照是要求原格式文件的双语对照吗，可以使用Tools->Batch->Generate Bilingual Files (for xliff)功能试试看。纯文本的双语对照在文件上右键导出
> 网页版机器翻译我暂时不想研究怎么集成

我的意思是做成那种可以输出doc或者.docx段段对照格式的文档，原文格式需要保留，这样会更有价值，因为格式处理也是一个很浪费时间的工作（有些客户就要求中英文段段对照格式）。只是单独生成word文档的话，我看软件的格式处理的挺不错的。

**Comment by xulihang** [comment]
>doc或者.docx段段对照格式

这个你用我前面提到的Tools->Batch->Generate Bilingual Files (for xliff)。这个操作就是用来生成双语对照文档的，不过原文和译文不是用换行分割的，而是`---separetor between source and target----`，需要后期进行替换。

**Comment by Joe007007007** [comment]
能直接生成原文格式一样的双语段段对照的word格式，这样会很方便，因为有时会和团队客户反复沟通，有些人只用word来看。每次自己手动去处理，很花时间，而且还会一不小心给弄错了。

**Comment by Joe007007007** [comment]
> 插件下载：
> [webmt_plugins.zip](https://github.com/xulihang/BasicCAT/files/5479084/webmt_plugins.zip)
> 
> 使用方法：
> 网页版机器翻译的URL里如果包含了原文译文语言和文本的参数，那可以较为容易地调用。译文也可以通过解析网页直接提取。
> Params那个文本框里包含如下内容：
> 
> ```
> auto,zh-CN,translation
> Hello World!
> ```
> 
> 它们依次是源语言代码、目标语言代码、最后的翻译结果的class name以及文本。
> 源语言和目标语言的代码需要自己根据情况进行调整
> 
> 如果要更换别的机器翻译引擎，需要修改URL Template（模板）以及Params（参数），这里提供一个百度的例子：
> 
> URL Template:
> 
> ```
> https://fanyi.baidu.com/#{sourceLang}/{targetLang}/{text}
> ```
> 
> Params:
> 
> ```
> en,zh,trans-content
> Hello World!
> ```

这个使用方法没有太看明白，有录屏吗？我想用这个google网页版的机器翻译插件来做自动预翻译。谢谢！

**Comment by xulihang** [comment]
生成Word格式的对照文件我前面讲了啊，使用Tools->Batch->Generate Bilingual Files (for xliff)这一功能，文件会生成在target目录下

**Comment by xulihang** [comment]
> 这个使用方法没有太看明白，有录屏吗？我想用这个google网页版的机器翻译插件来做自动预翻译。谢谢！

下载最新版BasicCAT，机器翻译里勾选web就可以调用了，新版可以自动设置译文语言代码。这个操作说明讲的是原理和怎么换用其它的网页版机器翻译。

**Comment by xulihang** [comment]
用网页版谷歌做预翻译，速度可能比较慢，我用网页版搜狗翻译是没问题的

**Comment by Joe007007007** [comment]
这个用google的web翻译速度太慢了，能不能把返回时间设置短一点？哦，对了omegaT有一个开源的插件google translate without key，这个包也可以支持google的机器翻译，不知道我们这个能否用？

**Comment by xulihang** [comment]
我看了下，OmeagT的google translate without key插件也是从网页版获取翻译的，不过它是直接调用了网页版使用的API，速度快很多，我移植过来了：https://github.com/xulihang/BasicCAT/tree/master/plugins/googlewithoutapiMT

下载：
[googlewithoutapiMTPlugin.zip](https://github.com/xulihang/BasicCAT/files/5657433/googlewithoutapiMTPlugin.zip)
