### ISSUE TITLE
The MacOS dmg file is corrupted and cannot be opened

### ISSUE THREAD

**Issue by ran-huang** [xulihang/BasicCAT#32]
Hi, great work there. 

I downloaded the file from https://www.basiccat.org/download/. I dragged it into the applications folder, but the app cannot be opened. Is there anything wrong?

My system: MacOS Catalina 10.15.7

![image](https://user-images.githubusercontent.com/59654584/110731873-0f4a5b00-825e-11eb-896e-4141885ecf9f.png)

**Comment by xulihang** [comment]
You could try previous builds or use the cross-platform version instead.

The macOS dmg is repacked on Windows. I haven't tested it on macOS.

To use the cross-platform version, you have to download the cross-platform zip and install jre 8.

**Comment by xulihang** [comment]
这个可能跟新的APFS格式有关，我重新打包了一个zip版本的：https://github.com/xulihang/BasicCAT/releases/download/v1.10.3/BasicCAT_mac.zip

**Comment by ran-huang** [comment]
谢谢~ 但文件还是 corrupt 打不开，我再试下跨平台版。

**Comment by xulihang** [comment]
I tried the dmg file on macOS Sierra and it works fine. I haven't upgraded my system for a long time. Maybe the latest version of macOS is no longer compatible with BasicCAT. I will try to make BasicCAT compatible with the latest macOS.

**Comment by xulihang** [comment]
I found a relevant issue: https://github.com/bancika/diy-layout-creator/issues/479

You could try this command:

`sudo xattr -rd com.apple.quarantine /Applications/BasicCAT.app`

**Comment by ran-huang** [comment]
I tried this command and the system didn't report the file is damaged. Instead, it gave no response at all. Thank you anyway. 

Maybe I should try using BasicCAT on a Windows VM.

**Comment by xulihang** [comment]
我在10.15.7的虚拟机上测试是可以运行的，你可以用DMG版本覆盖后再试一次

**Comment by xulihang** [comment]
Please run BasicCAT from the terminal and send me the output message if you are convenient.

```
cd /Applications/BasicCAT.app/Contents/MacOS
./BasicCAT
```

**Comment by ran-huang** [comment]
Sure. 

After running `sudo xattr` and then `./BasicCAT`, I got the following message and somehow **BasicCAT runs normally**:
```
(ArrayList) []
Loading jar finished
Initializing plugin cloudtranslationMT
Loading jar finished
Initializing plugin webMT
Loading jar finished
Initializing plugin niutransMT
Loading jar finished
Initializing plugin sogouMT
Loading jar finished
Initializing plugin papagoMT
Loading jar finished
Initializing plugin colorfulcloudsMT
Loading jar finished
Initializing plugin fiskmoMT
Loading jar finished
Initializing plugin tencentMT
Loading jar finished
Initializing plugin sogouDeepIMT
Loading jar finished
Initializing plugin watsonMT
Loading jar finished
Initializing plugin poFilter
plugins have changed!
(ArrayList) [cloudtranslationMT, webMT, niutransMT, sogouMT, papagoMT, colorfulcloudsMT, fiskmoMT, tencentMT, sogouDeepIMT, watsonMT, poFilter]
(RuntimeException) java.lang.RuntimeException: Object should first be initialized (JavaObject).
mainform has focus
(RuntimeException) java.lang.RuntimeException: Object should first be initialized (JavaObject).
mainform has focus
```
I think it's working now. 😸
