### ISSUE TITLE
deepin linux 如何运行它呢？

### ISSUE THREAD

**Issue by pgy866** [xulihang/BasicCAT#39]
deepin linux 如何运行它呢？
我尝试sudo chmod +x linux-install.sh
无效

**Comment by xulihang** [comment]
到这里下载Linux版jre: https://bell-sw.com/pages/downloads/#mn

然后这样运行：

java -jar BasicCAT.jar

**Comment by xulihang** [comment]
注意Linux下运行应用存在输入法的问题：https://github.com/xulihang/BasicCAT/issues/40

**Comment by pgy866** [comment]
非常感谢，平行语料软件本很少，LINUX更少。很好用，是否后期会支持软件界面的多语言化

**Comment by xulihang** [comment]
这是辅助翻译软件，不单单是语料。界面暂时没有做多语言的必要，搞翻译的基本都会英语
