### ISSUE TITLE
How to run BasicCAT on Linux

### ISSUE THREAD

**Issue by idimitriadis0** [xulihang/BasicCAT#41]
Hi,

I wanted to test BasicCAT on Linux (Ubuntu 20.04) in order to include it in the list of CAT tools available for Linux in TranslateOnLinux.org.

1. Running the linux-install.sh resulted in other directories being copied to /opt along with the BasicCAT-crossplatforms folder.
2. I did not find a readme including the requirements for Linux. Please consider including a readme file :-)
3. I cannot get the executable file to run, running the BasicCAT.jar or BasicCAT files. Could you please provide more information on running the program on Linux?

Thanks a lot!

Jean

**Comment by xulihang** [comment]
It is a Java program which needs JavaFX installed.

You need to install liberica jre (full) or openjre8 + openjfx8 to run it.

Command to run the program:

```
java -jar BasicCAT.jar
```

After running ` linux-install.sh`, you can use BasicCAT to run it directly.

**Comment by xulihang** [comment]
About running `linux-install.sh`, please put the files in a separate folder or other files will be copied.

**Comment by xulihang** [comment]
I have other tools which can run under Linux.

Aligner for text alignment: https://github.com/xulihang/Aligner
ImageTrans (OCR, typesetting, CAT): https://www.basiccat.org/imagetrans/

**Comment by idimitriadis0** [comment]
Thank you for your answers!

When I do java -jar BasicCAT.jar, I get:

_Error: JavaFX runtime components are missing, and are required to run this application_

This even after installing OpenJVX.

After checking online for a solution, it seems that:
1. JavaFX has been open sourced to OpenJVX.
2. Oracle has removed JavaFX from the JDK.

My default Java version is 17, and it produces the error above when I try to launch the .jar file.

However, using the Java 8 runtime (/usr/lib/jvm/java-8-oracle/jre/bin/java -jar BasicCAT.jar) was successful.

I can now run and test your CAT on Ubuntu 20.04.

Thank you also for mentioning the Aligner and ImageTrans. I was going to add ImageTrans for sure (it looks very impressive), and I just discovered the Aligner. It looks great and I will test it too! Integrating LFAligner and making the process interactive is excellent.

Thanks again!

**Comment by idimitriadis0** [comment]
I will soon add all three tools on the TranslateOnLinux website.
