### ISSUE TITLE
Integrate OpenXLIFF filters, a solution to support more file formats out of the box

### ISSUE THREAD

**Issue by idimitriadis0** [xulihang/BasicCAT#42]
One thing BasicCAT seems to be missing is native support for more file formats. The existing support for XLIFF and PO means BasicCAT can translate files processed via Okapi or projects created in some other CATs, but the process is convoluted.

I think it should be made more simple to translate common native file formats such as Word or Excel.

This could be achieved with the inclusion of [OpenXLIFF filters](https://github.com/rmraya/OpenXLIFF), an open source (Eclipse Public License - v 1.0) set of Java filters for creating, merging and validating XLIFF 1.2 and 2.0 files. They support a host of formats: https://github.com/rmraya/OpenXLIFF#supported-file-formats which would made BasicCAT able to handle a lot more formats out of the box.

If an integration is not preferred, you could also include, XLIFFManager (an open source UI for OpenXLIFF Filters written in TypeScript), a simpler tool than Okapi for creating XLIFF files and exporting target files.

**Comment by xulihang** [comment]
BasicCAT has integrated Okapi Tikal to support docx, pptx and xlsx files. But it may fail to run under Linux if the filename contains spaces.

I have tried OpenXLIFF before. It stores tag info in placeholder tags which BasiCAT may not be able to handle well.
