### ISSUE TITLE
设置完字体 在记忆管理里文字依然乱码 日文-中文

### ISSUE THREAD

**Issue by lhj5426** [xulihang/BasicCAT#48]
![image](https://user-images.githubusercontent.com/30548000/224357634-408c14bd-910e-4255-9bfd-541c1414f307.png)
 无奈 这里开个 问题吧 对不起 我很抱歉

**Comment by xulihang** [comment]
可能是BasicCAT自带的jre版本和新版windows存在兼容问题。可以下一个新版的jre替换原来的。下载地址：https://github.com/bell-sw/Liberica/releases/download/8u362%2B9/bellsoft-jre8u362+9-windows-amd64.zip

**Comment by lhj5426** [comment]
> 可能是BasicCAT自带的jre版本和新版windows存在兼容问题。可以下一个新版的jre替换原来的。_下载地址_：[https://github.com/bell-sw/Liberica/_releases_/_download_/8u362%2B9/bellsoft-jre8u362+9-windows-amd64-full.zip](https://github.com/bell-sw/Liberica/releases/download/8u362%2B9/bellsoft-jre8u362+9-windows-amd64-full.zip)


![image](https://user-images.githubusercontent.com/30548000/224473848-b5616c3c-376b-4e4a-9b0b-d81c446256a3.png)

![image](https://user-images.githubusercontent.com/30548000/224473828-1bca3379-4409-438d-a69f-7c1c91940ba3.png)
我的系统 
![image](https://user-images.githubusercontent.com/30548000/224473871-0a6e03ef-891b-4381-950e-dd17f0b18e82.png)
这两处还是乱码 但是在在 翻译记忆里的乱码通过右键打开了 又不乱码
![image](https://user-images.githubusercontent.com/30548000/224473955-31bd05f0-81e9-44ed-8663-b53c8f01a3e5.png)

![image](https://user-images.githubusercontent.com/30548000/224473936-fb5c4991-e327-4e0b-8647-e8dae18c345f.png)

**Comment by xulihang** [comment]
https://github.com/xulihang/ImageTrans-docs/issues/483
