### ISSUE TITLE
Admin rights issue or jav executable

### ISSUE THREAD

**Issue by liny888** [xulihang/BasicCAT#49]
Is it possible to have a windows executable that does not trigger admin rights? Using the cross platform version in a windows 10 machine without admin rights, some of the functions don't seem to work such as import review and search. Am I using it wrongly or this is an issue?

**Comment by xulihang** [comment]
Admin rights are not needed.

**Comment by liny888** [comment]
Hi, thanks for the reply. For the cross platform version, could you please help check if the search and replace is functioning properly? There seems to be no action/results when I click "find" .

**Comment by xulihang** [comment]
The cross-platform version has no difference from the other versions. I don't think it is related to the different versions.

![image](https://user-images.githubusercontent.com/5462205/224878552-fb20cf9a-9c82-470c-9099-a9ffd7a31466.png)

**Comment by liny888** [comment]
Thank you very much, I was searching in the wrong text box.
