### ISSUE TITLE
添加比较大的txt文件时，程序崩溃了

### ISSUE THREAD

**Issue by yifeitao** [xulihang/BasicCAT#5]
txt文件大小 36k，版本windows10 ，1.6beta，如果你复现不了，我可以提供txt文件。

**Comment by xulihang** [comment]
我测试几MB的TXT小说是没问题的，txt文件传给我看下吧

**Comment by yifeitao** [comment]
https://1drv.ms/t/s!AlnDHZ3lGCIkhuA35Lg4NN3j_06W-w

**Comment by xulihang** [comment]
450d5d7ffb16dea5e86d298564190e295d5d83ea
原因是这个文件开头有多个换行，之前没有考虑这个问题，结果List越界了。你把开头的几个换行删了就可以导入了。新的版本我过段时间再发布。

**Comment by yifeitao** [comment]
thanks
