### ISSUE TITLE
is it work on windows7

### ISSUE THREAD

**Issue by aniketstark** [xulihang/BasicCAT#51]
sorry this is not issue but i like to know is it work on windows7
because i was thinking to buy this software

**Comment by xulihang** [comment]
Are you referring to BasicCAT or ImageTrans? They both support Windows 7.

**Comment by aniketstark** [comment]
that was fast response ⚡
i was referring both
and i have some few questions, after that you can close this issue
1. is this one time purchase
2. whats difference between commercial and personal
3. do we need api's to translate

**Comment by xulihang** [comment]
You can find the answers on the FAQ page. But I will answer them here as well.

1. Yes. But for versions released 6 months after your purchase, you have to purchase it again.
2. There are no functional differences. It's just a restriction that you should not use the personal version for commercial projects. In addition, a commercial version can run on more devices (>10).
3. There are options which do not need API keys. You should read the docs for details.
