### ISSUE TITLE
Felix CAT Link Obsolete: Alternative Link

### ISSUE THREAD

**Issue by tajmone** [xulihang/BasicCAT#52]
In the documentation about _[Using Felix to Translate Word Files]_ the external link to Felix website is no longer usable, since the Felix app no longer lives there:

- https://felix-cat.com

The official Felix blog was last updated in 2015. In the [August 31, 2015 post], the author announced that Felix became open source and was released on BitBucket:

> # Felix is now open source
> 
> I released Felix as open source software under the MIT license.
> 
> The [source code can be found here](https://bitbucket.org/ginstrom/felix/).

But the link to the BitBucket repository is now dead (the repository no longer exists): 

- https://bitbucket.org/ginstrom/felix/

After some search, I've come across the following repository on GitHub:

- https://github.com/ultimatezen/felix

Although it links to the original [felix-cat.com] website, I have no idea if this repository is by the original Felix author, or if it's an independent fork.

In any case, it might be worth adding some clarifications in the BasicCAT documentation, since Felix can no longer be downloaded from the original website. If the GitHub repository link is usable, it might be worth adding a link to it.

[Using Felix to Translate Word Files]: https://basiccat-docs.readthedocs.io/en/latest/translatingFiles.html#felixword

[felix-cat.com]: https://felix-cat.com/

[August 31, 2015 post]: https://felix-cat.com/blog/?p=506 "Felix blog (2015-08-31): Felix is now open source"

**Comment by xulihang** [comment]
Actually, BasicCAT does not need to work with FelixCAT. I will delete it in the docs.

**Comment by xulihang** [comment]
Deleted.
