### ISSUE TITLE
About youdao api 

### ISSUE THREAD

**Issue by rywiki** [xulihang/BasicCAT#6]
Did youdao api change recently, but the program has not kept up? I added a meaningful key, but no feedback was returned. Word translation is not good either.

**Comment by xulihang** [comment]
I just tested it and it works fine. 
![youdao](https://user-images.githubusercontent.com/5462205/59186821-7416e400-8ba6-11e9-803f-4c3585b8e70b.png)

Please make sure that you have got the right appid and key from here: <https://ai.youdao.com/>, filled them correctly in BasicCAT and enabled them by checking relevant CheckBoxes.

**Comment by rywiki** [comment]
Sorry, it is my problem. Several platforms are licensed differently. There is a need to create an application and then create an instance and then bind. I didn't create an instance, so I can't use it. Thank you for your reply.
