### ISSUE TITLE
How does this app work

### ISSUE THREAD

**Issue by NKJibu02** [xulihang/BasicCAT#61]
I recently installed the app to my pc and attempted to translate some text from Japanese to English but nothing is happening. Is there any video guide on how to use it?
I tried following instructions on the page and github but nothing is working. Help please

**Comment by xulihang** [comment]
You can follow this documentation: https://docs.basiccat.org/en/latest/

**Comment by NKJibu02** [comment]
I tried that already. I don't know if its because am dumb to understand but it just feels like everytime i try to follow the instructions trying to translate a script (text file) in Japanese to English it just feels like am losing brain cells.

**Comment by xulihang** [comment]
What is th exact step you cannot follow?

**Comment by xulihang** [comment]
You have to manually enter the translation and generate the target file.
