### ISSUE TITLE
机翻选词能否添加来源标注

### ISSUE THREAD

**Issue by YLaido** [xulihang/BasicCAT#7]
勾选多个机翻选项之后，大段划词一次性出现太多结果，不知道结果对应哪个api，而且划词速度过慢的话popup可以占据整个屏幕。

有时划词会出现多个重复结果，例如只勾选了两个api，但是双击选取某一四字词时会出现四个结果。

希望能实现的是，像选定之后会出现一个[像这个取词插件](https://github.com/waynecz/dadda-translate-crx)的浮动按钮，我想应该会提高划词准度。如果能美化一下取词popup，可以对比不同api机翻结果就更好了。

**Comment by xulihang** [comment]
划词目前没有对划词过程是否结束的判断，会把划词过程中的词都调用机器翻译，我一般是用shift键来一次选中的。这个尚待完善。

像那个取词插件一样就变成在线词典了，目前有在线词典功能，按CTRL+D调用。比较机器翻译的话可以做成一个单独的窗口。BasicCAT的划词取义的popup主要是用于快速调用机器翻译翻译片段。

**Comment by YLaido** [comment]
提及那个取词插件的按钮只是作为一个参考，这样应该能解决划词popup泛滥屏幕的现象。
在线词典功能的话一定要新建窗口的话，建议只提取页面中有用的元素就可以了，这样就不需要在小窗口中来回滚动，体验也会更好一些

**Comment by xulihang** [comment]
嗯，popup条目数量可以做一个限制，像现在AutoComplete的popup数量是可以限制的。

现在的在线词典其实就是个浏览器，因为不同网页的内容不一样，挺难提取的。

**Comment by YLaido** [comment]
感觉像那个取词插件的触发机制就可以了，等用户划词选定完成后再选择是否翻译。

提取网页内容的话直接构造请求就可以了，用python一类的脚本语言就能完成请求加提取元素，只是不同页面需要分开写逻辑。

xulihang <notifications@github.com> 于2019年6月13日周四 下午4:51写道：

**Comment by xulihang** [comment]
用快捷键触发是可以考虑。我之前其实测试过等用户鼠标点击松开这一事件发生后才触发，但这样就不能用键盘来选择，就没采用。

在线词典提取内容其实相当于把桌面版做成可以自适应窗口的版本。如果原来就有提供移动版，效果会好很多，比如有道提供的：<http://dict.youdao.com/m/search?keyfrom=dict.mindex&vendor=&q=test>。自己处理还是比较麻烦。

![词典](https://user-images.githubusercontent.com/5462205/59438943-f7466d00-8e26-11e9-89bb-4a0dad07d4e6.png)

**Comment by xulihang** [comment]
22df4d5c688240a164b89d5753a9e68f2a48275d

添加使用F1触发查词的选项

![无标题](https://user-images.githubusercontent.com/5462205/60341673-e29ad500-99e1-11e9-9c5f-401dd384ad4f.png)

**Comment by xulihang** [comment]
0ac53894ab4951c36b949436f92211cc3d75f502 

增加了在结果前显示来源的选项。来源用一个圆圈圈住的首字母表示。还好这些引擎的首字母基本都不一样，能起到区分作用。

![无标题](https://user-images.githubusercontent.com/5462205/60350843-07e60e00-99f7-11e9-98be-3cad156bec94.png)
