### ISSUE TITLE
无法打开导入的po翻译

### ISSUE THREAD

**Issue by ccc1924** [xulihang/BasicCAT#8]
导入po文件后点击打开出现'the workfile does not exist.Mayby it's still in building'
![image](https://user-images.githubusercontent.com/8176393/60154689-acf7bf80-981a-11e9-92db-506feaf1101d.png)
此文件在poedit可以正常打开

**Comment by xulihang** [comment]
po文件可以发给我一下吗，我测试okapi生成的po文件没什么问题。

**Comment by ccc1924** [comment]
已发送至xulihanghai@gmail.com

**Comment by xulihang** [comment]
我测试是可以打开的，你用的最新版本的BasicCAT吗，最新版会弹出一个导入文件的提示框，提示框消失就表示导入完成了。

![捕获](https://user-images.githubusercontent.com/5462205/60161410-1f23d080-982a-11e9-8936-08d811e073c1.PNG)

**Comment by xulihang** [comment]
这个文件比较复杂，而且msgstr已经有内容填充了，可能BasicCAT生成的文件会有问题

**Comment by xulihang** [comment]
这个文件还是用OmegaT处理比较好，对代码格式的展示效果好。
![捕获](https://user-images.githubusercontent.com/5462205/60164529-54cbb800-9830-11e9-92f5-6ee728c9653a.PNG)

**Comment by ccc1924** [comment]
谢谢您，我试试OmegaT

**Comment by xulihang** [comment]
有时间会改善下对po文件的支持，支持多行msgstr的处理以及译文获取，添加对\n和\t等控制符的效果展示，类似以下效果，需要配合等宽字体。


![捕获](https://user-images.githubusercontent.com/5462205/60256946-105e1c00-9905-11e9-9823-1864e7f35226.PNG)

**Comment by xulihang** [comment]
bc52bbcd753a25a5679db7d60d6711462f3facf8 

解决了po文件特殊格式符号的转义和多行msgstr的处理问题，可以下载以下附件替换原来的插件

[poFilterPlugin.zip](https://github.com/xulihang/BasicCAT/files/3341316/poFilterPlugin.zip)
