### ISSUE TITLE
老哥，不是我说，感觉挺难用的

### ISSUE THREAD

**Issue by sanbeichahegongheguo** [xulihang/BasicCAT#9]
首先不知道为什么，各个来源下载的时候总是下不下来。千辛万苦下下来，感觉使用上也不是特别便利。我试着导入一个PDF，分段不智能。而且欢迎节目也没有OmegaT那么好。

需要改进的地方还是挺多，加油吧。我现在这台新电脑至今都没有成功下载下来你们这个软件。已经改用OmegaT了。

**Comment by xulihang** [comment]
谢谢指出。下载目前提供了百度网盘和Github Releases的链接，对于有的网络的确比较慢，而且因为是java的桌面程序，所以体积比较大，这个目前也没有什么好办法。

PDF是比较难处理的格式，BasicCAT只提供了文本抽取工具，将文本抽取出来还需要手工调整，保存为txt用于翻译。对于PDF存在的换行问题，点reflow按钮可以去除，但也有可能去除一些标题后面的换行。这个我试过各种CAT软件，包括OmegaT，都没有能很好处理的。

![image](https://user-images.githubusercontent.com/5462205/61170545-51a92980-a59d-11e9-8588-452df50402c9.png)

![image](https://user-images.githubusercontent.com/5462205/61170532-39d1a580-a59d-11e9-88a5-6adca5054a55.png)

使用指南因为个人精力有限，只写了[在线文档](http://docs.basiccat.org/zh_CN/latest/)，没有做进程序里。

OmegaT是很棒的CAT软件，2002年就开发出来了。我一直使用的CAT就是OmegaT，还有雪人CAT。BasicCAT是前年才开发的，还在不断完善中，它也有它自己的优势。比如对于机器翻译的集成、对于IDML文件的支持、支持本地Git、实时性更强的术语和翻译记忆共享等，和雪人CAT免费版相比，功能就更加丰富，也更加开放。不过因为用户少，目前开发主要是满足我个人的需求。如果你的任务OmegaT能满足，的确OmegaT是更好的选择，不过也欢迎继续尝试BasicCAT。

**Comment by sanbeichahegongheguo** [comment]
哇，好细致的回复。话说我昨天晚上终于下下来了。已经装上了，开始尝试了。我应该会交替着和OmegaT用。因为我就是一个喜欢尝试新鲜事务的好奇人。
